project:
  type: website
  output-dir: docs

execute: 
  freeze: auto
  
website:
  title: "Suvaditya Mukherjee"
  site-url: "https://suvadityamuk.com"
  description: "Suvaditya Mukherjee"
  page-navigation: true
  google-analytics: "G-XHQD3SPP05"
  favicon: favicon.png
  # page-footer: 
  #   center: "Copyright © 2023, Suvaditya Mukherjee"
  #   background: light
  #   border: true
  navbar:
    search: true
    background: primary
    fontcolor: secondary
    pinned: true
    right:
      - text: About
        file: about.qmd
      - text: Talks
        file: talks.qmd
      - text: Writings
        file: writings.qmd
      - icon: github
        href: https://github.com/suvadityamuk
      - icon: twitter
        href: https://twitter.com/halcyonrayes
      - icon: linkedin
        href: https://www.linkedin.com/in/suvadityamukherjee

format:
  html:
    theme: 
      light: default
    css: styles.css



